export const GET_CLIP_LIST_REQUEST = 'GET_CLIP_LIST_REQUEST';
export const GET_CLIP_LIST_SUCCESS = 'GET_CLIP_LIST_SUCCESS';
export const GET_CLIP_LIST_FAILURE = 'GET_CLIP_LIST_FAILURE';

export const GET_PRESENTATION_CLIP_REQUEST = 'GET_PRESENTATION_CLIP_REQUEST';
export const GET_PRESENTATION_CLIP_FAILURE = 'GET_PRESENTATION_CLIP_FAILURE';
export const GET_PRESENTATION_CLIP_SUCCESS = 'GET_PRESENTATION_CLIP_SUCCESS';

export const CHANGE_PRESENTATION_CLIP_REQUEST = 'CHANGE_PRESENTATION_CLIP_REQUEST';
export const CHANGE_PRESENTATION_CLIP_FAILURE = 'CHANGE_PRESENTATION_CLIP_FAILURE';
export const CHANGE_PRESENTATION_CLIP_SUCCESS = 'CHANGE_PRESENTATION_CLIP_SUCCESS';

export const ADD_CLIP_REQUEST = 'ADD_CLIP_REQUEST';
export const ADD_CLIP_FAILURE = 'ADD_CLIP_FAILURE';
export const ADD_CLIP_SUCCESS = 'ADD_CLIP_SUCCESS';

export const REMOVE_CLIP_REQUEST = 'REMOVE_CLIP_REQUEST';
export const REMOVE_CLIP_FAILURE = 'REMOVE_CLIP_FAILURE';
export const REMOVE_CLIP_SUCCESS = 'REMOVE_CLIP_SUCCESS';
