export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const GET_ARTICLES_NUM_REQUEST = 'GET_ARTICLES_NUM_REQUEST';
export const GET_ARTICLES_NUM_SUCCESS = 'GET_ARTICLES_NUM_SUCCESS';
export const GET_ARTICLES_NUM_FAILURE = 'GET_ARTICLES_NUM_FAILURE';