export const ACCEPT_ADD_CLIP_FORM_CHANGES = 'ACCEPT_ADD_CLIP_FORM_CHANGES';

export const CLEAR_ADD_CLIP_FORM = 'CLEAR_ADD_CLIP_FORM';


export const VALIDATION_FORM_SUCCESS = 'VALIDATION_FORM_SUCCESS';

export const VALIDATION_FORM_FAILURE = 'VALIDATION_FORM_FAILURE';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';